### ISSUE TITLE
TODO Feature: Implement and support url resources pack and change system EncryptKey support for resources pack

### ISSUE THREAD

**Issue by SenseiTarzan** [SymplyX/Symply-PM#17]

**Comment by Refaltor77** [comment]
cdn are already supported, can be make the config cleaner and why change the encryption system?

**Comment by SenseiTarzan** [comment]
The system maintains backward compatibility with the Pocketmine-mp system but like the cdn system I have to put additional information I made it easier to add the encryption keys And before it was worth making a file with a separate file for the encryption key

**Comment by SenseiTarzan** [comment]
[#20](https://github.com/SymplyX/Symply/pull/20)
