### ISSUE TITLE
Todo: Add system addons (Items, Block, Entity)

### ISSUE THREAD

**Issue by AzaleeX** [SymplyX/Symply-PM#5]
Addition of an addon system (Items, Blocks, Entity) for Symply, allowing users to integrate custom elements into Minecraft Bedrock.

**Comment by SenseiTarzan** [comment]
[here's how to start making custom blocks](https://github.com/SymplyX/Symply/tree/next-dev-behavior-system/symply/behavior)

**Comment by AzaleeX** [comment]
Added in Symply 0.0.5 update
